### ISSUE TITLE
std::function is really slow

### ISSUE THREAD

**Issue by nilsdeppe** [geoffrey4444/spectre-cpp-basics#1]
`std::function` is really, really slow, which is one of the reasons lambdas exist. In general I would recommend against teaching that std::function exists and instead either write a simple function object, wrap a call in a lambda, or do just about anything other than use std::function :)

https://github.com/geoffrey4444/spectre-cpp-basics/blob/3308eecc7ae165b44d8f9191b7b1811fa356d121/Examples/Day1/trap.cpp#L26

**Comment by geoffrey4444** [comment]
> `std::function` is really, really slow, which is one of the reasons lambdas exist. In general I would recommend against teaching that std::function exists and instead either write a simple function object, wrap a call in a lambda, or do just about anything other than use std::function :)
> 
> 
> 
> https://github.com/geoffrey4444/spectre-cpp-basics/blob/3308eecc7ae165b44d8f9191b7b1811fa356d121/Examples/Day1/trap.cpp#L26

Thanks for the advice! Do you have an idea that doesn’t use classes or lambdas, which I won’t have introduced yet?

**Comment by nilsdeppe** [comment]
You can just use a function pointer. I always forget the notation because it's terrible, but since we use function pointers quite a bit in SpECTRE I think that's actually worth introducing

**Comment by geoffrey4444** [comment]
Switched to function pointers in 5b51b341ea3fc9e16afc1ea9a47731e69a42045d

**Comment by nilsdeppe** [comment]
Looks good!
